// Code generated by protoc-gen-go. DO NOT EDIT.
// source: TSession.proto

package config

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TSessionSessionType int32

const (
	TSession_CONNECTOR TSessionSessionType = 0
	TSession_LOGIC     TSessionSessionType = 1
	TSession_CMD       TSessionSessionType = 2
)

var TSessionSessionType_name = map[int32]string{
	0: "CONNECTOR",
	1: "LOGIC",
	2: "CMD",
}

var TSessionSessionType_value = map[string]int32{
	"CONNECTOR": 0,
	"LOGIC":     1,
	"CMD":       2,
}

func (x TSessionSessionType) String() string {
	return proto.EnumName(TSessionSessionType_name, int32(x))
}

func (TSessionSessionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cb2b1dadcb3d5c27, []int{0, 0}
}

type TSession struct {
	Cid                  string              `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	SrcSubRouter         string              `protobuf:"bytes,2,opt,name=srcSubRouter,proto3" json:"srcSubRouter,omitempty"`
	DstSubRouter         string              `protobuf:"bytes,3,opt,name=dstSubRouter,proto3" json:"dstSubRouter,omitempty"`
	Body                 []byte              `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	St                   TSessionSessionType `protobuf:"varint,5,opt,name=st,proto3,enum=config.TSessionSessionType" json:"st,omitempty"`
	ReplyToken           string              `protobuf:"bytes,6,opt,name=replyToken,proto3" json:"replyToken,omitempty"`
	Router               string              `protobuf:"bytes,7,opt,name=router,proto3" json:"router,omitempty"`
	LogicBindId          string              `protobuf:"bytes,8,opt,name=logicBindId,proto3" json:"logicBindId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TSession) Reset()         { *m = TSession{} }
func (m *TSession) String() string { return proto.CompactTextString(m) }
func (*TSession) ProtoMessage()    {}
func (*TSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb2b1dadcb3d5c27, []int{0}
}

func (m *TSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TSession.Unmarshal(m, b)
}
func (m *TSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TSession.Marshal(b, m, deterministic)
}
func (m *TSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TSession.Merge(m, src)
}
func (m *TSession) XXX_Size() int {
	return xxx_messageInfo_TSession.Size(m)
}
func (m *TSession) XXX_DiscardUnknown() {
	xxx_messageInfo_TSession.DiscardUnknown(m)
}

var xxx_messageInfo_TSession proto.InternalMessageInfo

func (m *TSession) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *TSession) GetSrcSubRouter() string {
	if m != nil {
		return m.SrcSubRouter
	}
	return ""
}

func (m *TSession) GetDstSubRouter() string {
	if m != nil {
		return m.DstSubRouter
	}
	return ""
}

func (m *TSession) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *TSession) GetSt() TSessionSessionType {
	if m != nil {
		return m.St
	}
	return TSession_CONNECTOR
}

func (m *TSession) GetReplyToken() string {
	if m != nil {
		return m.ReplyToken
	}
	return ""
}

func (m *TSession) GetRouter() string {
	if m != nil {
		return m.Router
	}
	return ""
}

func (m *TSession) GetLogicBindId() string {
	if m != nil {
		return m.LogicBindId
	}
	return ""
}

type CmdMsg struct {
	RunRoutineNum        int64    `protobuf:"varint,1,opt,name=runRoutineNum,proto3" json:"runRoutineNum,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdMsg) Reset()         { *m = CmdMsg{} }
func (m *CmdMsg) String() string { return proto.CompactTextString(m) }
func (*CmdMsg) ProtoMessage()    {}
func (*CmdMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb2b1dadcb3d5c27, []int{1}
}

func (m *CmdMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdMsg.Unmarshal(m, b)
}
func (m *CmdMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdMsg.Marshal(b, m, deterministic)
}
func (m *CmdMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdMsg.Merge(m, src)
}
func (m *CmdMsg) XXX_Size() int {
	return xxx_messageInfo_CmdMsg.Size(m)
}
func (m *CmdMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdMsg.DiscardUnknown(m)
}

var xxx_messageInfo_CmdMsg proto.InternalMessageInfo

func (m *CmdMsg) GetRunRoutineNum() int64 {
	if m != nil {
		return m.RunRoutineNum
	}
	return 0
}

func (m *CmdMsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("config.TSessionSessionType", TSessionSessionType_name, TSessionSessionType_value)
	proto.RegisterType((*TSession)(nil), "config.TSession")
	proto.RegisterType((*CmdMsg)(nil), "config.CmdMsg")
}

func init() { proto.RegisterFile("TSession.proto", fileDescriptor_cb2b1dadcb3d5c27) }

var fileDescriptor_cb2b1dadcb3d5c27 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xcb, 0x6a, 0xf3, 0x30,
	0x10, 0x85, 0x7f, 0xdb, 0x89, 0x93, 0x4c, 0x2e, 0x98, 0x59, 0xfc, 0x68, 0x51, 0x8a, 0x31, 0x5d,
	0x64, 0x51, 0x42, 0x69, 0xdf, 0x20, 0x6e, 0x29, 0x81, 0x26, 0x06, 0xc5, 0x2f, 0x10, 0x5b, 0xaa,
	0x11, 0x4d, 0x24, 0x23, 0xc9, 0x0b, 0xbf, 0x56, 0x9f, 0xb0, 0x58, 0xee, 0xc5, 0x59, 0xf9, 0xf8,
	0x3b, 0x07, 0xce, 0xcc, 0x08, 0x56, 0xf9, 0x91, 0x1b, 0x23, 0x94, 0xdc, 0xd4, 0x5a, 0x59, 0x85,
	0x61, 0xa9, 0xe4, 0xbb, 0xa8, 0x92, 0x4f, 0x1f, 0xa6, 0x3f, 0x16, 0x46, 0x10, 0x94, 0x82, 0x11,
	0x2f, 0xf6, 0xd6, 0x33, 0xda, 0x49, 0x4c, 0x60, 0x61, 0x74, 0x79, 0x6c, 0x0a, 0xaa, 0x1a, 0xcb,
	0x35, 0xf1, 0x9d, 0x75, 0xc5, 0xba, 0x0c, 0x33, 0xf6, 0x2f, 0x13, 0xf4, 0x99, 0x21, 0x43, 0x84,
	0x51, 0xa1, 0x58, 0x4b, 0x46, 0xb1, 0xb7, 0x5e, 0x50, 0xa7, 0xf1, 0x1e, 0x7c, 0x63, 0xc9, 0x38,
	0xf6, 0xd6, 0xab, 0xc7, 0x9b, 0x4d, 0x3f, 0xcf, 0xe6, 0x77, 0x4c, 0xd3, 0x7f, 0xf3, 0xb6, 0xe6,
	0xd4, 0x37, 0x16, 0x6f, 0x01, 0x34, 0xaf, 0xcf, 0x6d, 0xae, 0x3e, 0xb8, 0x24, 0xa1, 0xeb, 0x18,
	0x10, 0xfc, 0x0f, 0xa1, 0xee, 0xfb, 0x27, 0xce, 0xfb, 0xfe, 0xc3, 0x18, 0xe6, 0x67, 0x55, 0x89,
	0x72, 0x2b, 0x24, 0xdb, 0x31, 0x32, 0x75, 0xe6, 0x10, 0x25, 0x0f, 0x30, 0x1f, 0x94, 0xe1, 0x12,
	0x66, 0x69, 0x76, 0x38, 0xbc, 0xa4, 0x79, 0x46, 0xa3, 0x7f, 0x38, 0x83, 0xf1, 0x5b, 0xf6, 0xba,
	0x4b, 0x23, 0x0f, 0x27, 0x10, 0xa4, 0xfb, 0xe7, 0xc8, 0x4f, 0xb6, 0x10, 0xa6, 0x17, 0xb6, 0x37,
	0x15, 0xde, 0xc1, 0x52, 0x37, 0xb2, 0x5b, 0x52, 0x48, 0x7e, 0x68, 0x2e, 0xee, 0x76, 0x01, 0xbd,
	0x86, 0xdd, 0xf6, 0xec, 0x64, 0x4f, 0xee, 0x7a, 0x0b, 0xea, 0x74, 0x11, 0xba, 0x77, 0x78, 0xfa,
	0x0a, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x15, 0x80, 0xf2, 0x99, 0x01, 0x00, 0x00,
}
